@echo off
echo 🔧 Updating Flutter dependencies to fix chat connection...
echo.
cd flutter_app
echo 📦 Getting dependencies...
flutter pub get
echo.
echo 🧹 Cleaning build cache...
flutter clean
echo.
echo 📦 Getting dependencies again...
flutter pub get
echo.
echo 🚀 Starting Flutter app with real backend connection...
flutter run
pause