#!/usr/bin/env python3
"""
Skin Disease Classifier — Inference Module
============================================
Production-ready inference wrapper for the EfficientNet-B3 skin lesion
classifier trained on HAM10000.

Loads the trained checkpoint, preprocesses raw image bytes, and returns
structured predictions with confidence scores, severity assessment,
clinical recommendations, and a mandatory medical disclaimer.

MEDICAL DISCLAIMER: This system is intended for research and educational
purposes only. It does NOT provide medical diagnoses. Predictions should
NEVER replace professional dermatological evaluation. Always consult a
qualified healthcare provider for any skin concerns.
"""

import io
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2

# ---------------------------------------------------------------------------
# Import model architecture from training module
# ---------------------------------------------------------------------------
# We re-define the model architecture here so the classifier is self-contained
# and doesn't require the training module at inference time.
import timm

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# ===================================================================
# Constants & Configuration
# ===================================================================
CLASS_NAMES: List[str] = [
    "akiec",  # Actinic Keratoses & Intraepithelial Carcinoma
    "bcc",    # Basal Cell Carcinoma
    "bkl",    # Benign Keratosis-like Lesions
    "df",     # Dermatofibroma
    "mel",    # Melanoma
    "nv",     # Melanocytic Nevi
    "vasc",   # Vascular Lesions
]

CLASS_DISPLAY_NAMES: Dict[str, str] = {
    "akiec": "Actinic Keratoses / Intraepithelial Carcinoma",
    "bcc":   "Basal Cell Carcinoma",
    "bkl":   "Benign Keratosis-like Lesions",
    "df":    "Dermatofibroma",
    "mel":   "Melanoma",
    "nv":    "Melanocytic Nevi",
    "vasc":  "Vascular Lesions",
}

NUM_CLASSES: int = len(CLASS_NAMES)
DEFAULT_IMAGE_SIZE: int = 224
DEFAULT_IMAGENET_MEAN: Tuple[float, ...] = (0.485, 0.456, 0.406)
DEFAULT_IMAGENET_STD: Tuple[float, ...] = (0.229, 0.224, 0.225)

MEDICAL_DISCLAIMER: str = (
    "IMPORTANT: This analysis is generated by an AI system trained for "
    "research and educational purposes only. It is NOT a medical diagnosis "
    "and should NEVER be used as a substitute for professional medical advice, "
    "diagnosis, or treatment. Skin lesions can only be accurately diagnosed "
    "through clinical examination and, when necessary, histopathological "
    "analysis by a qualified dermatologist. If you have any concerns about "
    "a skin lesion, please consult a licensed healthcare provider immediately."
)


# ===================================================================
# Severity Classification
# ===================================================================
SEVERITY_MAP: Dict[str, str] = {
    "mel":   "high",    # Melanoma — potentially life-threatening
    "bcc":   "high",    # Basal Cell Carcinoma — malignant
    "akiec": "high",    # Actinic Keratoses — pre-cancerous / carcinoma
    "bkl":   "medium",  # Benign Keratosis — non-cancerous but monitor
    "df":    "low",     # Dermatofibroma — benign
    "nv":    "low",     # Melanocytic Nevi — common moles
    "vasc":  "low",     # Vascular Lesions — usually benign
}

# ===================================================================
# Clinical Recommendations by Condition
# ===================================================================
RECOMMENDATIONS_DB: Dict[str, List[str]] = {
    "mel": [
        "URGENT: Melanoma is the most serious form of skin cancer. "
        "Seek immediate evaluation by a dermatologist or oncologist.",
        "Do NOT attempt to treat, remove, or biopsy this lesion yourself.",
        "Request a dermoscopic examination and possible excisional biopsy.",
        "If confirmed, early-stage melanoma has a very high survival rate "
        "with proper surgical excision.",
        "Document the lesion — photograph it with a ruler for scale and "
        "note any recent changes in size, shape, or colour.",
        "Inform your physician about the ABCDE criteria findings: "
        "Asymmetry, Border irregularity, Colour variation, Diameter >6mm, "
        "and Evolution over time.",
    ],
    "bcc": [
        "Basal Cell Carcinoma is the most common form of skin cancer but "
        "rarely metastasises. Schedule a dermatology appointment promptly.",
        "Treatment options include surgical excision, Mohs micrographic "
        "surgery, cryotherapy, or topical therapies depending on size "
        "and location.",
        "Protect the area from further UV exposure — use SPF 50+ sunscreen "
        "and wear protective clothing.",
        "Regular follow-up examinations are essential as BCC can recur.",
        "Avoid tanning beds and minimise prolonged sun exposure.",
    ],
    "akiec": [
        "Actinic Keratosis is considered a pre-cancerous lesion that can "
        "progress to squamous cell carcinoma if left untreated.",
        "Consult a dermatologist for evaluation — treatment may include "
        "cryotherapy, topical chemotherapy (5-FU), photodynamic therapy, "
        "or curettage.",
        "Apply broad-spectrum SPF 50+ sunscreen daily to all exposed skin.",
        "Perform regular self-examinations for new or changing lesions.",
        "Consider a full-body skin examination if you have multiple "
        "actinic keratoses.",
    ],
    "bkl": [
        "Benign keratosis-like lesions (e.g. seborrheic keratosis, solar "
        "lentigo) are generally harmless and do not require treatment.",
        "However, have a dermatologist confirm the diagnosis to rule out "
        "melanoma or other malignancies that may mimic benign lesions.",
        "If the lesion is cosmetically bothersome, removal options include "
        "cryotherapy, curettage, or laser therapy.",
        "Monitor for any changes in size, colour, or texture.",
        "Maintain regular sun protection to prevent new lesions.",
    ],
    "df": [
        "Dermatofibromas are common, benign skin growths that typically "
        "require no treatment.",
        "The lesion may feel firm to the touch and often appears on the "
        "legs — this is normal.",
        "If the lesion becomes painful, grows rapidly, or changes "
        "appearance, consult a dermatologist.",
        "Surgical excision is an option if the lesion is symptomatic "
        "or cosmetically undesirable, though it may leave a scar.",
        "No specific prevention measures are needed for dermatofibromas.",
    ],
    "nv": [
        "Melanocytic nevi (moles) are extremely common and usually benign.",
        "Monitor your moles using the ABCDE rule: Asymmetry, Border "
        "irregularity, Colour variation, Diameter >6mm, Evolution.",
        "Perform monthly self-skin examinations and note any new or "
        "changing moles.",
        "Use SPF 30+ sunscreen daily to reduce UV-related changes "
        "in existing moles.",
        "Schedule an annual full-body skin check with a dermatologist, "
        "especially if you have many moles or a family history of melanoma.",
    ],
    "vasc": [
        "Vascular lesions (e.g. cherry angiomas, pyogenic granulomas) are "
        "typically benign and often require no treatment.",
        "If bleeding, growing rapidly, or causing discomfort, consult a "
        "dermatologist for evaluation.",
        "Treatment options, if desired, include laser therapy, "
        "electrocautery, or cryotherapy.",
        "These lesions are generally not related to sun exposure.",
        "No specific preventive measures are required.",
    ],
}


# ===================================================================
# Model Architecture (self-contained for inference)
# ===================================================================
class _SkinEfficientNet(nn.Module):
    """
    EfficientNet-B3 with custom classification head.
    Matches the training architecture exactly for checkpoint loading.
    """

    def __init__(
        self,
        num_classes: int = NUM_CLASSES,
        drop_head_1: float = 0.4,
        drop_head_2: float = 0.3,
        hidden_dim: int = 512,
    ):
        super().__init__()
        self.backbone = timm.create_model(
            "efficientnet_b3",
            pretrained=False,  # weights loaded from checkpoint
            num_classes=0,
            global_pool="avg",
        )
        backbone_dim = self.backbone.num_features  # 1536

        self.classifier = nn.Sequential(
            nn.Dropout(p=drop_head_1),
            nn.Linear(backbone_dim, hidden_dim),
            nn.ReLU(inplace=True),
            nn.Dropout(p=drop_head_2),
            nn.Linear(hidden_dim, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.backbone(x)
        logits = self.classifier(features)
        return logits


# ===================================================================
# SkinDiseaseClassifier — Main Inference Class
# ===================================================================
class SkinDiseaseClassifier:
    """
    Production inference wrapper for the EfficientNet-B3 skin lesion
    classification model.

    Handles model loading, image preprocessing, prediction, severity
    assessment, and recommendation generation.

    Usage:
        classifier = SkinDiseaseClassifier(model_path="models/skin_model.pth")
        result = classifier.predict(image_bytes)
        print(result["top_prediction"])
        print(result["disclaimer"])  # Always present

    Args:
        model_path:  Path to the trained checkpoint (.pth file)
        device:      'cuda', 'cpu', or None for auto-detection
    """

    def __init__(
        self,
        model_path: str = "models/skin_model.pth",
        device: Optional[str] = None,
    ):
        self.model_path = Path(model_path)

        # ---- Device selection ---------------------------------------------
        if device is not None:
            self.device = torch.device(device)
        else:
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        logger.info(f"SkinDiseaseClassifier — device: {self.device}")

        # ---- Load checkpoint & model --------------------------------------
        self.model: Optional[nn.Module] = None
        self.class_names: List[str] = CLASS_NAMES
        self.class_display_names: Dict[str, str] = CLASS_DISPLAY_NAMES
        self.image_size: int = DEFAULT_IMAGE_SIZE
        self.imagenet_mean: Tuple[float, ...] = DEFAULT_IMAGENET_MEAN
        self.imagenet_std: Tuple[float, ...] = DEFAULT_IMAGENET_STD

        self._load_model()

        # ---- Build preprocessing pipeline ---------------------------------
        self.transform = self._build_transform()

        logger.info("SkinDiseaseClassifier ready for inference")

    # ------------------------------------------------------------------
    # Model Loading
    # ------------------------------------------------------------------
    def _load_model(self) -> None:
        """Load the trained model from checkpoint."""
        if not self.model_path.exists():
            logger.warning(
                f"Model checkpoint not found at {self.model_path}. "
                f"The classifier will not function until a valid checkpoint "
                f"is provided. Train the model first using train_skin_model.py."
            )
            return

        logger.info(f"Loading checkpoint from {self.model_path} ...")
        checkpoint = torch.load(
            self.model_path,
            map_location=self.device,
            weights_only=False,
        )

        # Extract metadata from checkpoint if available
        if "class_names" in checkpoint:
            self.class_names = checkpoint["class_names"]
        if "class_display_names" in checkpoint:
            self.class_display_names = checkpoint["class_display_names"]
        if "image_size" in checkpoint:
            self.image_size = checkpoint["image_size"]
        if "imagenet_mean" in checkpoint:
            self.imagenet_mean = tuple(checkpoint["imagenet_mean"])
        if "imagenet_std" in checkpoint:
            self.imagenet_std = tuple(checkpoint["imagenet_std"])

        # Build and load model
        self.model = _SkinEfficientNet(num_classes=len(self.class_names))
        self.model.load_state_dict(checkpoint["model_state_dict"])
        self.model = self.model.to(self.device)
        self.model.eval()

        best_auc = checkpoint.get("best_val_auc", "N/A")
        epoch = checkpoint.get("epoch", "N/A")
        logger.info(
            f"Model loaded successfully — Epoch: {epoch}, "
            f"Best Val AUC: {best_auc}"
        )

    # ------------------------------------------------------------------
    # Preprocessing
    # ------------------------------------------------------------------
    def _build_transform(self) -> A.Compose:
        """Build the deterministic inference preprocessing pipeline."""
        return A.Compose(
            [
                A.Resize(self.image_size, self.image_size),
                A.Normalize(mean=self.imagenet_mean, std=self.imagenet_std),
                ToTensorV2(),
            ]
        )

    def preprocess(self, image_bytes: bytes) -> torch.Tensor:
        """
        Convert raw image bytes to a preprocessed tensor ready for inference.

        Args:
            image_bytes: Raw image file content (JPEG, PNG, etc.)

        Returns:
            Preprocessed tensor of shape (1, 3, image_size, image_size)
        """
        # Decode image bytes
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        image_np = np.array(image)

        # Apply Albumentations pipeline
        augmented = self.transform(image=image_np)
        tensor = augmented["image"]  # (3, H, W)

        # Add batch dimension
        tensor = tensor.unsqueeze(0)  # (1, 3, H, W)

        return tensor

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------
    @torch.no_grad()
    def predict(self, image_bytes: bytes) -> Dict:
        """
        Run inference on raw image bytes and return a structured prediction
        result including confidence scores, severity, and recommendations.

        Args:
            image_bytes: Raw image file content (JPEG, PNG, etc.)

        Returns:
            Dictionary with the following structure:
            {
                "top_prediction": {
                    "condition": str,            # Full display name
                    "condition_code": str,        # Short code (e.g. "mel")
                    "confidence": float,          # 0.0 to 1.0
                },
                "all_predictions": [
                    {
                        "condition": str,
                        "condition_code": str,
                        "confidence": float,
                    },
                    ...  # sorted by confidence descending
                ],
                "severity": "low" | "medium" | "high",
                "severity_details": str,
                "recommendations": [str, ...],
                "confidence_interpretation": str,
                "disclaimer": str,
            }

        MEDICAL DISCLAIMER: This prediction is for research/educational
        purposes only and must NOT be used for medical diagnosis.
        """
        # ---- Guard: model not loaded? ------------------------------------
        if self.model is None:
            return self._build_error_response(
                "Model not loaded. Please provide a valid checkpoint file "
                "trained using train_skin_model.py."
            )

        try:
            # ---- Preprocess -----------------------------------------------
            input_tensor = self.preprocess(image_bytes)
            input_tensor = input_tensor.to(self.device)

            # ---- Forward pass ---------------------------------------------
            logits = self.model(input_tensor)            # (1, C)
            probabilities = F.softmax(logits, dim=1)     # (1, C)
            probs_np = probabilities.cpu().numpy()[0]     # (C,)

            # ---- Build sorted predictions ---------------------------------
            sorted_indices = np.argsort(probs_np)[::-1]

            all_predictions = []
            for idx in sorted_indices:
                code = self.class_names[idx]
                all_predictions.append(
                    {
                        "condition": self.class_display_names.get(code, code),
                        "condition_code": code,
                        "confidence": round(float(probs_np[idx]), 6),
                    }
                )

            top = all_predictions[0]
            top_code = top["condition_code"]
            top_confidence = top["confidence"]

            # ---- Severity ------------------------------------------------
            severity = self._assess_severity(top_code, top_confidence)
            severity_details = self._get_severity_details(
                top_code, severity, top_confidence
            )

            # ---- Recommendations -----------------------------------------
            recommendations = self._get_recommendations(
                top_code, top_confidence, severity
            )

            # ---- Confidence interpretation --------------------------------
            confidence_text = self._interpret_confidence(top_confidence)

            # ---- Build response -------------------------------------------
            result: Dict = {
                "top_prediction": {
                    "condition": top["condition"],
                    "condition_code": top_code,
                    "confidence": top_confidence,
                },
                "all_predictions": all_predictions,
                "severity": severity,
                "severity_details": severity_details,
                "recommendations": recommendations,
                "confidence_interpretation": confidence_text,
                "disclaimer": MEDICAL_DISCLAIMER,
            }

            return result

        except Exception as e:
            logger.error(f"Prediction failed: {e}", exc_info=True)
            return self._build_error_response(str(e))

    # ------------------------------------------------------------------
    # Severity Assessment
    # ------------------------------------------------------------------
    def _assess_severity(self, condition_code: str, confidence: float) -> str:
        """
        Determine clinical severity based on diagnosis category and
        model confidence.

        High-risk lesions (melanoma, BCC, AKIEC) are always elevated
        when confidence is reasonable. Low-confidence predictions for
        malignant categories are still flagged as medium to encourage
        clinical follow-up.
        """
        base_severity = SEVERITY_MAP.get(condition_code, "medium")

        if confidence < 0.3:
            # Very low confidence — uncertain, recommend professional check
            return "medium"

        if base_severity == "high" and confidence >= 0.3:
            # Even moderate confidence for malignant categories → high
            return "high"

        if base_severity == "medium":
            return "medium"

        if base_severity == "low" and confidence >= 0.7:
            return "low"

        # Edge case: low base severity but model is uncertain
        return "medium"

    def _get_severity_details(
        self, condition_code: str, severity: str, confidence: float
    ) -> str:
        """Return a human-readable severity explanation."""
        details = {
            "high": (
                f"The AI model has identified features consistent with "
                f"{self.class_display_names.get(condition_code, condition_code)} "
                f"(confidence: {confidence:.1%}). This category is associated "
                f"with malignant or pre-cancerous lesions and requires urgent "
                f"professional evaluation by a dermatologist."
            ),
            "medium": (
                f"The AI model has identified features that may be consistent "
                f"with {self.class_display_names.get(condition_code, condition_code)} "
                f"(confidence: {confidence:.1%}). While these lesions are often "
                f"benign, professional evaluation is recommended to confirm "
                f"the diagnosis and rule out more serious conditions."
            ),
            "low": (
                f"The AI model suggests features consistent with "
                f"{self.class_display_names.get(condition_code, condition_code)} "
                f"(confidence: {confidence:.1%}). This category is generally "
                f"benign. Continue routine skin monitoring and maintain annual "
                f"dermatological check-ups."
            ),
        }
        return details.get(severity, details["medium"])

    # ------------------------------------------------------------------
    # Recommendations
    # ------------------------------------------------------------------
    def _get_recommendations(
        self, condition_code: str, confidence: float, severity: str
    ) -> List[str]:
        """
        Build a prioritised list of clinical recommendations based on
        the predicted condition and confidence level.
        """
        recs: List[str] = []

        # ---- Condition-specific recommendations --------------------------
        condition_recs = RECOMMENDATIONS_DB.get(condition_code, [])
        recs.extend(condition_recs)

        # ---- Low-confidence advisory -------------------------------------
        if confidence < 0.5:
            recs.insert(
                0,
                "⚠️ The model's confidence is relatively low for this "
                "prediction. The image quality, lighting, or angle may have "
                "affected the analysis. Consider retaking the photo in "
                "natural lighting with the lesion clearly in focus.",
            )

        # ---- Universal recommendations -----------------------------------
        recs.append(
            "Maintain a record of all skin lesions — photograph them "
            "periodically to track any changes in size, shape, or colour."
        )
        recs.append(
            "Practice sun safety: apply SPF 30+ sunscreen daily, wear "
            "protective clothing, and avoid peak UV hours (10 AM – 4 PM)."
        )

        # ---- Severity-driven urgency -------------------------------------
        if severity == "high":
            recs.insert(
                0,
                "🔴 HIGH PRIORITY: Please schedule an appointment with a "
                "dermatologist as soon as possible for a professional "
                "evaluation of this lesion.",
            )
        elif severity == "medium":
            recs.insert(
                0,
                "🟡 RECOMMENDED: Schedule a dermatology appointment at your "
                "earliest convenience for a professional evaluation.",
            )

        return recs

    # ------------------------------------------------------------------
    # Confidence Interpretation
    # ------------------------------------------------------------------
    def _interpret_confidence(self, confidence: float) -> str:
        """Human-readable confidence level interpretation."""
        if confidence >= 0.90:
            return (
                "Very High Confidence — The model is highly confident in this "
                "classification. However, professional verification is still "
                "strongly recommended."
            )
        elif confidence >= 0.75:
            return (
                "High Confidence — The model shows strong agreement with this "
                "classification. A professional dermatological evaluation is "
                "recommended for confirmation."
            )
        elif confidence >= 0.50:
            return (
                "Moderate Confidence — The model shows reasonable agreement but "
                "there is some uncertainty. Professional evaluation is important "
                "to confirm or rule out this classification."
            )
        elif confidence >= 0.30:
            return (
                "Low Confidence — The model is uncertain about this classification. "
                "Multiple conditions may appear similar. Professional evaluation "
                "is essential."
            )
        else:
            return (
                "Very Low Confidence — The model cannot reliably classify this "
                "image. This may be due to image quality, unusual presentation, "
                "or a condition outside the model's training data. Please consult "
                "a dermatologist."
            )

    # ------------------------------------------------------------------
    # Error Response Builder
    # ------------------------------------------------------------------
    def _build_error_response(self, error_message: str) -> Dict:
        """
        Build a structured error response that maintains the expected
        output schema and always includes the medical disclaimer.
        """
        return {
            "top_prediction": {
                "condition": "Analysis Unavailable",
                "condition_code": "error",
                "confidence": 0.0,
            },
            "all_predictions": [],
            "severity": "medium",
            "severity_details": (
                f"Analysis could not be completed: {error_message}. "
                f"Please consult a dermatologist for professional evaluation."
            ),
            "recommendations": [
                "The AI analysis could not be completed. This does not indicate "
                "the absence of a medical condition.",
                f"Error details: {error_message}",
                "Please consult a qualified dermatologist for a thorough "
                "skin evaluation.",
                "If you believe the image was valid, try retaking the photo "
                "with better lighting and focus.",
            ],
            "confidence_interpretation": "Analysis could not be performed.",
            "disclaimer": MEDICAL_DISCLAIMER,
        }

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------
    def is_ready(self) -> bool:
        """Check if the classifier is loaded and ready for inference."""
        return self.model is not None

    def get_model_info(self) -> Dict:
        """Return metadata about the loaded model."""
        info: Dict = {
            "model_loaded": self.model is not None,
            "model_path": str(self.model_path),
            "device": str(self.device),
            "num_classes": len(self.class_names),
            "class_names": self.class_names,
            "class_display_names": self.class_display_names,
            "image_size": self.image_size,
            "disclaimer": MEDICAL_DISCLAIMER,
        }

        if self.model is not None:
            total_params = sum(p.numel() for p in self.model.parameters())
            info["total_parameters"] = total_params
            info["total_parameters_human"] = f"{total_params / 1e6:.1f}M"

        return info

    def predict_from_file(self, file_path: str) -> Dict:
        """
        Convenience method: predict from a file path instead of bytes.

        Args:
            file_path: Path to an image file (JPEG, PNG, etc.)

        Returns:
            Same structured prediction dictionary as predict()
        """
        path = Path(file_path)
        if not path.exists():
            return self._build_error_response(f"File not found: {file_path}")

        with open(path, "rb") as f:
            image_bytes = f.read()

        return self.predict(image_bytes)


# ===================================================================
# Module-level singleton (lazy initialisation)
# ===================================================================
_classifier_instance: Optional[SkinDiseaseClassifier] = None


def get_skin_classifier(
    model_path: str = "models/skin_model.pth",
) -> SkinDiseaseClassifier:
    """
    Get or create a global SkinDiseaseClassifier singleton.

    This avoids loading the model multiple times in a server context.
    """
    global _classifier_instance
    if _classifier_instance is None:
        _classifier_instance = SkinDiseaseClassifier(model_path=model_path)
    return _classifier_instance


# ===================================================================
# CLI Demo
# ===================================================================
if __name__ == "__main__":
    """
    Quick demo / smoke test:
        python -m src.ai_models.skin_classifier --image path/to/lesion.jpg
    """
    import argparse
    import json

    parser = argparse.ArgumentParser(
        description="Skin Disease Classifier — Inference Demo"
    )
    parser.add_argument(
        "--image",
        type=str,
        required=True,
        help="Path to a dermoscopic image file",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="models/skin_model.pth",
        help="Path to the trained model checkpoint",
    )

    args = parser.parse_args()

    # Initialise classifier
    classifier = SkinDiseaseClassifier(model_path=args.model)

    if not classifier.is_ready():
        print("ERROR: Model not loaded. Train the model first.")
        print(f"Expected checkpoint at: {args.model}")
        exit(1)

    # Run prediction
    result = classifier.predict_from_file(args.image)

    # Pretty-print result
    print("\n" + "=" * 70)
    print("  SKIN LESION CLASSIFICATION RESULT")
    print("=" * 70)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    print("=" * 70)
    print(f"\n⚕️  {result['disclaimer']}\n")
