"""
Health Passport PDF router.

GET /api/v1/health-passport/generate?period_days=7
"""

import io
import logging
import os
import tempfile
from collections import Counter
from datetime import date, datetime, timedelta
from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response

from src.api.dependencies import get_analysis_repo, get_current_user
from src.database.models import AnalysisRecord, User
from src.database.repositories.analysis_repository import AnalysisRepository

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/health-passport", tags=["health-passport"])

_DISCLAIMER = (
    "MEDICAL DISCLAIMER: This health passport is generated by AI WellnessVision for "
    "informational purposes only. It does not constitute medical advice, diagnosis, or "
    "treatment. Always consult a qualified healthcare professional."
)

_RECS = [
    "Drink at least 8 glasses (2 litres) of water daily to maintain proper hydration.",
    "Engage in at least 30 minutes of moderate physical activity 5 days per week.",
    "Maintain a balanced diet rich in fruits, vegetables, whole grains and lean protein.",
    "Ensure 7–8 hours of quality sleep every night to support immune and mental health.",
    "Schedule a full clinical health check-up with your primary physician every 6 months.",
]


# ─── PDF helpers ───────────────────────────────────────────────────────────────

def _type_value(at) -> str:
    return at.value if hasattr(at, "value") else str(at)


def _build_chart_png(counts: dict) -> str | None:
    """Render a bar chart to a temp PNG file and return the path, or None on failure."""
    if not counts:
        return None
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        labels = [k.title() for k in counts.keys()]
        values = list(counts.values())
        colours = ["#10B981", "#3B82F6", "#F59E0B", "#8B5CF6"][:len(labels)]

        fig, ax = plt.subplots(figsize=(5.5, 2.8))
        bars = ax.bar(labels, values, color=colours, edgecolor="none", width=0.5)
        ax.set_ylabel("Analyses", fontsize=9)
        ax.set_title("Analyses by Type", fontsize=10, fontweight="bold")
        ax.set_ylim(0, max(values) + max(1, max(values) * 0.2))
        ax.spines[["top", "right"]].set_visible(False)
        for bar, v in zip(bars, values):
            ax.text(
                bar.get_x() + bar.get_width() / 2, v + 0.05,
                str(v), ha="center", va="bottom", fontsize=9,
            )
        plt.tight_layout()

        fd, path = tempfile.mkstemp(suffix=".png")
        os.close(fd)
        plt.savefig(path, format="png", dpi=110, bbox_inches="tight")
        plt.close(fig)
        return path
    except Exception as exc:
        logger.warning("Chart generation failed: %s", exc)
        return None


def _generate_pdf(user: User, records: List[AnalysisRecord], period_days: int) -> bytes:
    from fpdf import FPDF

    end_date = date.today()
    start_date = end_date - timedelta(days=period_days)

    # Aggregate
    type_counts: Counter = Counter()
    total_conf = 0.0
    conf_count = 0
    for r in records:
        type_counts[_type_value(r.analysis_type)] += 1
        if r.confidence is not None:
            total_conf += r.confidence
            conf_count += 1

    avg_conf_pct = round((total_conf / conf_count) * 100, 1) if conf_count else 0.0
    most_common_type = type_counts.most_common(1)[0][0].title() if type_counts else "N/A"

    full_name = (
        f"{getattr(user, 'first_name', '') or ''} "
        f"{getattr(user, 'last_name', '') or ''}"
    ).strip() or user.email

    # ── Build PDF ──────────────────────────────────────────────────────────────
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_margins(14, 14, 14)

    # 1. GREEN HEADER STRIPE
    pdf.set_fill_color(16, 185, 129)
    pdf.rect(0, 0, 210, 32, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_xy(14, 5)
    pdf.cell(0, 9, "AI WellnessVision", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_x(14)
    pdf.cell(0, 7, "Personal Health Passport", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # 2. USER INFO
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, f"Patient: {full_name}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(
        0, 6,
        f"Period: {start_date.strftime('%d %b %Y')} — {end_date.strftime('%d %b %Y')} ({period_days} days)",
        ln=True,
    )
    pdf.cell(
        0, 6,
        f"Generated: {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}",
        ln=True,
    )
    pdf.ln(4)

    # 3. SUMMARY
    pdf.set_fill_color(236, 253, 245)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  Summary", fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(2)
    pdf.cell(0, 6, f"   Total Analyses:          {len(records)}", ln=True)
    pdf.cell(0, 6, f"   Average Confidence:       {avg_conf_pct}%", ln=True)
    pdf.cell(0, 6, f"   Most Analysed Type:       {most_common_type}", ln=True)
    pdf.ln(4)

    # 4. BAR CHART
    chart_path = _build_chart_png(dict(type_counts))
    if chart_path:
        try:
            pdf.image(chart_path, x=14, w=120)
        except Exception as exc:
            logger.warning("Chart embed failed: %s", exc)
        finally:
            try:
                os.unlink(chart_path)
            except OSError:
                pass
        pdf.ln(4)

    # 5. TYPE BREAKDOWN
    pdf.set_fill_color(236, 253, 245)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  Breakdown by Type", fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(2)
    for atype in ["skin", "eye", "food", "emotion"]:
        count = type_counts.get(atype, 0)
        pdf.cell(0, 6, f"   • {atype.title():<12}  {count} session(s)", ln=True)
    pdf.ln(4)

    # 6. TOP 5 RECOMMENDATIONS
    pdf.set_fill_color(236, 253, 245)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  Top 5 Wellness Recommendations", fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(2)
    for i, rec in enumerate(_RECS, 1):
        pdf.multi_cell(0, 6, f"   {i}. {rec}")
    pdf.ln(4)

    # 7. MEDICAL DISCLAIMER FOOTER
    pdf.set_fill_color(243, 244, 246)
    pdf.set_text_color(80, 80, 80)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, _DISCLAIMER, fill=True)
    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(0, 5, "Generated by AI WellnessVision — For informational purposes only", ln=True)

    return bytes(pdf.output())


# ─── Endpoint ─────────────────────────────────────────────────────────────────

@router.get("/generate")
async def generate_health_passport(
    period_days: int = Query(default=7, ge=1, le=90, description="Report window in days"),
    current_user: User = Depends(get_current_user),
    analysis_repo: AnalysisRepository = Depends(get_analysis_repo),
) -> Response:
    """Generate and stream a PDF Health Passport for the authenticated user."""
    try:
        cutoff = datetime.utcnow() - timedelta(days=period_days)
        all_records = await analysis_repo.get_user_history(user_id=current_user.id, limit=500)
        records = [
            r for r in all_records
            if r.created_at.replace(tzinfo=None) >= cutoff
        ]

        pdf_bytes = _generate_pdf(user=current_user, records=records, period_days=period_days)

    except Exception as exc:
        logger.error("Health passport PDF generation failed for user %s: %s", current_user.id, exc, exc_info=True)
        raise HTTPException(status_code=500, detail="PDF generation failed. Please try again.")

    filename = f"health_passport_{date.today().isoformat()}.pdf"
    logger.info(
        "Health passport generated — user=%s records=%d days=%d bytes=%d",
        current_user.id, len(records), period_days, len(pdf_bytes),
    )
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
